name: Check for Open Source Vulnerabilities with Snyk
on: 
  push:
    branches:
      master
jobs:
  oss-security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check for High Severity OSS Vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --fail-on=upgradable --file=Dockerfile
    - name: Upload Container Scan results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
          sarif_file: snyk.sarif
